"""
PM-OS CCE ResearchPlanGenerator (v5.0)

Creates structured two-pass research plans for deep feature discovery.
Given questionnaire answers and available sources, generates internal
(Brain, Jira, GitHub, Confluence, etc.) and external (web, competitor,
market validation) research tasks. Config-driven source detection.

Usage:
    from pm_os_cce.tools.research.research_plan_generator import (
        ResearchPlanGenerator, ResearchPlan
    )
"""

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from pm_os_base.tools.core.config_loader import get_config
except ImportError:
    from core.config_loader import get_config

try:
    from pm_os_base.tools.core.path_resolver import get_paths
except ImportError:
    from core.path_resolver import get_paths

try:
    from pm_os_cce.tools.research.discovery_questionnaire import QuestionnaireResult
except ImportError:
    from research.discovery_questionnaire import QuestionnaireResult

logger = logging.getLogger(__name__)


class ResearchSource(Enum):
    """Available research sources for the deep research swarm."""

    BRAIN = "brain"
    MASTER_SHEET = "master_sheet"
    JIRA = "jira"
    GITHUB = "github"
    CONFLUENCE = "confluence"
    GDOCS = "gdocs"
    SLACK = "slack"
    STATSIG = "statsig"
    WEB = "web"
    GEMINI_DEEP_RESEARCH = "gemini_deep_research"
    CODEBASE = "codebase"
    FIGMA = "figma"


class SourceStatus(Enum):
    """Connectivity status for a research source."""

    AVAILABLE = "available"
    CONFIGURED = "configured"
    UNAVAILABLE = "unavailable"


@dataclass
class SourceProbe:
    """Result of probing a single source for availability."""

    source: ResearchSource
    status: SourceStatus
    reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source": self.source.value,
            "status": self.status.value,
            "reason": self.reason,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SourceProbe":
        return cls(
            source=ResearchSource(data["source"]),
            status=SourceStatus(data["status"]),
            reason=data.get("reason", ""),
        )


@dataclass
class ResearchTask:
    """
    A single research task within the research plan.

    Attributes:
        id: Unique task identifier (e.g., "int-brain-01")
        source: Which source to search
        query: The search query or prompt
        purpose: Why this search is needed
        pass_number: 1 for broad first pass, 2 for targeted follow-up
        category: "internal" or "external"
        estimated_seconds: Rough time estimate
        depends_on: Task IDs that must complete before this one
    """

    id: str
    source: ResearchSource
    query: str
    purpose: str
    pass_number: int = 1
    category: str = "internal"
    estimated_seconds: int = 30
    depends_on: Optional[List[str]] = None

    def to_dict(self) -> Dict[str, Any]:
        result = {
            "id": self.id,
            "source": self.source.value,
            "query": self.query,
            "purpose": self.purpose,
            "pass_number": self.pass_number,
            "category": self.category,
            "estimated_seconds": self.estimated_seconds,
        }
        if self.depends_on:
            result["depends_on"] = self.depends_on
        return result

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ResearchTask":
        return cls(
            id=data["id"],
            source=ResearchSource(data["source"]),
            query=data["query"],
            purpose=data["purpose"],
            pass_number=data.get("pass_number", 1),
            category=data.get("category", "internal"),
            estimated_seconds=data.get("estimated_seconds", 30),
            depends_on=data.get("depends_on"),
        )


@dataclass
class ResearchPlan:
    """
    A structured research plan with internal and external tasks.

    Generated by ResearchPlanGenerator and executed by DeepResearchSwarm.
    """

    feature_title: str
    questionnaire_summary: Dict[str, Any] = field(default_factory=dict)
    available_sources: List[SourceProbe] = field(default_factory=list)
    internal_tasks: List[ResearchTask] = field(default_factory=list)
    external_tasks: List[ResearchTask] = field(default_factory=list)
    first_pass_hits: Dict[str, int] = field(default_factory=dict)
    estimated_total_seconds: int = 0
    created_at: datetime = field(default_factory=datetime.now)
    approved: bool = False
    challenged: bool = False
    challenge_feedback: Optional[str] = None

    @property
    def total_tasks(self) -> int:
        return len(self.internal_tasks) + len(self.external_tasks)

    @property
    def pass_1_tasks(self) -> List[ResearchTask]:
        return [
            t
            for t in self.internal_tasks + self.external_tasks
            if t.pass_number == 1
        ]

    @property
    def pass_2_tasks(self) -> List[ResearchTask]:
        return [
            t
            for t in self.internal_tasks + self.external_tasks
            if t.pass_number == 2
        ]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "feature_title": self.feature_title,
            "questionnaire_summary": self.questionnaire_summary,
            "available_sources": [s.to_dict() for s in self.available_sources],
            "internal_tasks": [t.to_dict() for t in self.internal_tasks],
            "external_tasks": [t.to_dict() for t in self.external_tasks],
            "first_pass_hits": self.first_pass_hits,
            "estimated_total_seconds": self.estimated_total_seconds,
            "created_at": self.created_at.isoformat(),
            "approved": self.approved,
            "challenged": self.challenged,
            "challenge_feedback": self.challenge_feedback,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ResearchPlan":
        return cls(
            feature_title=data.get("feature_title", ""),
            questionnaire_summary=data.get("questionnaire_summary", {}),
            available_sources=[
                SourceProbe.from_dict(s)
                for s in data.get("available_sources", [])
            ],
            internal_tasks=[
                ResearchTask.from_dict(t)
                for t in data.get("internal_tasks", [])
            ],
            external_tasks=[
                ResearchTask.from_dict(t)
                for t in data.get("external_tasks", [])
            ],
            first_pass_hits=data.get("first_pass_hits", {}),
            estimated_total_seconds=data.get("estimated_total_seconds", 0),
            created_at=datetime.fromisoformat(
                data.get("created_at", datetime.now().isoformat())
            ),
            approved=data.get("approved", False),
            challenged=data.get("challenged", False),
            challenge_feedback=data.get("challenge_feedback"),
        )


# ============================================================================
# RESEARCH PLAN GENERATOR
# ============================================================================


class ResearchPlanGenerator:
    """
    Generates research plans from questionnaire answers and available sources.

    Probes the PM-OS environment to detect which integrations are available,
    runs a first-pass scan for quick hits, then generates a two-pass research
    plan with internal and external tasks.
    """

    def __init__(self, user_path: Optional[Path] = None):
        if user_path:
            self.user_path = user_path
        else:
            try:
                paths = get_paths()
                self.user_path = Path(paths.get("user", ""))
            except Exception:
                self.user_path = Path(
                    os.getenv("PM_OS_USER", os.path.expanduser("~/pm-os/user"))
                )
        self._config = None

    def _load_config(self) -> Dict[str, Any]:
        """Load user config via config_loader."""
        if self._config is not None:
            return self._config

        try:
            self._config = get_config() or {}
        except Exception:
            self._config = {}
        return self._config

    def probe_available_sources(self) -> List[SourceProbe]:
        """
        Detect which research sources are configured and available.

        Checks config and environment variables to determine
        which integrations can be used for research.

        Returns:
            List of SourceProbe with availability status for each source
        """
        config = self._load_config()
        integrations = config.get("integrations", {})
        probes: List[SourceProbe] = []

        # Brain - available if brain path exists
        try:
            paths = get_paths()
            brain_path = Path(paths.get("brain", ""))
        except Exception:
            brain_path = self.user_path / "brain"

        if brain_path.exists():
            probes.append(
                SourceProbe(ResearchSource.BRAIN, SourceStatus.AVAILABLE)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.BRAIN,
                    SourceStatus.UNAVAILABLE,
                    "Brain directory not found",
                )
            )

        # Master Sheet - available if Google enabled
        if integrations.get("google", {}).get("enabled"):
            probes.append(
                SourceProbe(
                    ResearchSource.MASTER_SHEET, SourceStatus.CONFIGURED
                )
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.MASTER_SHEET,
                    SourceStatus.UNAVAILABLE,
                    "Google integration not enabled",
                )
            )

        # Jira
        if integrations.get("jira", {}).get("enabled"):
            probes.append(
                SourceProbe(ResearchSource.JIRA, SourceStatus.CONFIGURED)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.JIRA,
                    SourceStatus.UNAVAILABLE,
                    "Jira integration not enabled",
                )
            )

        # GitHub
        if integrations.get("github", {}).get("enabled"):
            probes.append(
                SourceProbe(ResearchSource.GITHUB, SourceStatus.CONFIGURED)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.GITHUB,
                    SourceStatus.UNAVAILABLE,
                    "GitHub integration not enabled",
                )
            )

        # Confluence
        if integrations.get("confluence", {}).get("enabled"):
            probes.append(
                SourceProbe(
                    ResearchSource.CONFLUENCE, SourceStatus.CONFIGURED
                )
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.CONFLUENCE,
                    SourceStatus.UNAVAILABLE,
                    "Confluence integration not enabled",
                )
            )

        # GDocs
        if integrations.get("google", {}).get("enabled"):
            probes.append(
                SourceProbe(ResearchSource.GDOCS, SourceStatus.CONFIGURED)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.GDOCS,
                    SourceStatus.UNAVAILABLE,
                    "Google integration not enabled",
                )
            )

        # Slack
        if integrations.get("slack", {}).get("enabled"):
            probes.append(
                SourceProbe(ResearchSource.SLACK, SourceStatus.CONFIGURED)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.SLACK,
                    SourceStatus.UNAVAILABLE,
                    "Slack integration not enabled",
                )
            )

        # Statsig
        if integrations.get("statsig", {}).get("enabled"):
            probes.append(
                SourceProbe(ResearchSource.STATSIG, SourceStatus.CONFIGURED)
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.STATSIG,
                    SourceStatus.UNAVAILABLE,
                    "Statsig integration not enabled",
                )
            )

        # Web search - always available via WebFetch or model_bridge
        probes.append(
            SourceProbe(ResearchSource.WEB, SourceStatus.AVAILABLE)
        )

        # Gemini Deep Research - check for API key
        if os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY"):
            probes.append(
                SourceProbe(
                    ResearchSource.GEMINI_DEEP_RESEARCH,
                    SourceStatus.AVAILABLE,
                )
            )
        else:
            probes.append(
                SourceProbe(
                    ResearchSource.GEMINI_DEEP_RESEARCH,
                    SourceStatus.CONFIGURED,
                    "Gemini API key not found -- will fall back to Claude at execution time",
                )
            )

        return probes

    def first_pass_scan(
        self,
        questionnaire: QuestionnaireResult,
        sources: List[SourceProbe],
    ) -> Dict[str, Any]:
        """
        Run lightweight queries across available sources to gauge data availability.

        Args:
            questionnaire: Structured answers from the discovery questionnaire
            sources: List of probed source availability

        Returns:
            Dict with hit counts and sample results per source
        """
        results: Dict[str, Any] = {}
        search_terms = _build_search_terms(questionnaire)

        available = {
            s.source
            for s in sources
            if s.status != SourceStatus.UNAVAILABLE
        }

        # Brain scan (local, fast)
        if ResearchSource.BRAIN in available:
            try:
                from documents.research_aggregator import search_brain

                hits = search_brain(search_terms, limit=5)
                results["brain"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"Brain first-pass scan failed: {e}")
                results["brain"] = {"hit_count": 0, "samples": [], "error": str(e)}

        # Jira scan
        if ResearchSource.JIRA in available:
            try:
                from documents.research_aggregator import search_jira

                hits = search_jira(search_terms, limit=5)
                results["jira"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"Jira first-pass scan failed: {e}")
                results["jira"] = {"hit_count": 0, "samples": [], "error": str(e)}

        # GitHub scan
        if ResearchSource.GITHUB in available:
            try:
                from documents.research_aggregator import search_github

                hits = search_github(search_terms, limit=5)
                results["github"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"GitHub first-pass scan failed: {e}")
                results["github"] = {"hit_count": 0, "samples": [], "error": str(e)}

        # Slack scan
        if ResearchSource.SLACK in available:
            try:
                from documents.research_aggregator import search_slack

                hits = search_slack(search_terms, limit=5)
                results["slack"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"Slack first-pass scan failed: {e}")
                results["slack"] = {"hit_count": 0, "samples": [], "error": str(e)}

        # Confluence scan
        if ResearchSource.CONFLUENCE in available:
            try:
                from documents.research_aggregator import search_confluence

                hits = search_confluence(search_terms, limit=5)
                results["confluence"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"Confluence first-pass scan failed: {e}")
                results["confluence"] = {"hit_count": 0, "samples": [], "error": str(e)}

        # GDocs scan
        if ResearchSource.GDOCS in available:
            try:
                from documents.research_aggregator import search_gdrive

                hits = search_gdrive(search_terms, limit=5)
                results["gdocs"] = {
                    "hit_count": len(hits),
                    "samples": hits[:3],
                }
            except Exception as e:
                logger.warning(f"GDocs first-pass scan failed: {e}")
                results["gdocs"] = {"hit_count": 0, "samples": [], "error": str(e)}

        return results

    def generate_plan(
        self,
        questionnaire: QuestionnaireResult,
        first_pass_data: Dict[str, Any],
    ) -> ResearchPlan:
        """
        Generate a two-pass research plan from questionnaire + first-pass data.

        Pass 1: Broad queries across all available sources
        Pass 2: Targeted follow-up based on pass 1 gaps (placeholder tasks)

        Args:
            questionnaire: Structured answers
            first_pass_data: Hit counts and samples from first_pass_scan

        Returns:
            ResearchPlan with internal and external tasks
        """
        config = self._load_config()
        integrations = config.get("integrations", {})
        search_terms = _build_search_terms(questionnaire)
        feature_desc = questionnaire.feature_description or questionnaire.user_problem
        brand = questionnaire.brand or questionnaire.product or "the product"
        market = questionnaire.market or "target market"

        internal_tasks: List[ResearchTask] = []
        external_tasks: List[ResearchTask] = []
        task_counter = {"int": 0, "ext": 0}

        def _int_id() -> str:
            task_counter["int"] += 1
            return f"int-{task_counter['int']:02d}"

        def _ext_id() -> str:
            task_counter["ext"] += 1
            return f"ext-{task_counter['ext']:02d}"

        # ----------------------------------------------------------------
        # INTERNAL PASS 1: Broad discovery across internal sources
        # ----------------------------------------------------------------

        # Brain entity search
        if first_pass_data.get("brain", {}).get("hit_count", 0) >= 0:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.BRAIN,
                    query=search_terms,
                    purpose="Find related Brain entities, prior decisions, and stakeholder context",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=15,
                )
            )

        # Jira search
        if "jira" in first_pass_data:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.JIRA,
                    query=f"{search_terms} {questionnaire.product}".strip(),
                    purpose="Find related Jira tickets, epics, and past work",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=30,
                )
            )

        # GitHub search
        if "github" in first_pass_data:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.GITHUB,
                    query=search_terms,
                    purpose="Find related code, PRs, and technical implementations",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=30,
                )
            )

        # Confluence search
        if "confluence" in first_pass_data:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.CONFLUENCE,
                    query=search_terms,
                    purpose="Find related documentation, specs, and design docs",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=30,
                )
            )

        # Slack search
        if "slack" in first_pass_data:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.SLACK,
                    query=search_terms,
                    purpose="Find related team discussions and decisions",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=20,
                )
            )

        # GDocs search
        if "gdocs" in first_pass_data:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.GDOCS,
                    query=search_terms,
                    purpose="Find related Google Docs, presentations, and spreadsheets",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=30,
                )
            )

        # Statsig search (experiments)
        if "statsig" in first_pass_data or questionnaire.product:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.STATSIG,
                    query=f"{questionnaire.product} {search_terms}".strip(),
                    purpose="Find related A/B tests, feature flags, and experiment results",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=20,
                )
            )

        # Codebase architecture analysis
        github_config = integrations.get("github", {})
        tracked_repos = github_config.get("tracked_repos", [])
        target_repo = questionnaire.raw_answers.get("target_repo", "")
        if tracked_repos or target_repo:
            codebase_query = target_repo or (tracked_repos[0] if tracked_repos else "")
            if codebase_query:
                internal_tasks.append(
                    ResearchTask(
                        id=_int_id(),
                        source=ResearchSource.CODEBASE,
                        query=codebase_query,
                        purpose="Analyze codebase architecture: components, routing, services, feature flags",
                        pass_number=1,
                        category="internal",
                        estimated_seconds=30,
                    )
                )

        # Figma design file analysis
        figma_link = questionnaire.raw_answers.get("figma_link", "")
        if figma_link:
            internal_tasks.append(
                ResearchTask(
                    id=_int_id(),
                    source=ResearchSource.FIGMA,
                    query=figma_link,
                    purpose="Analyze Figma design file: screens, component usage, design system coverage",
                    pass_number=1,
                    category="internal",
                    estimated_seconds=20,
                )
            )

        # ----------------------------------------------------------------
        # EXTERNAL PASS 1: Market and competitor research
        # ----------------------------------------------------------------

        # Competitor analysis
        competitor_query = _build_competitor_query(questionnaire)
        if competitor_query:
            external_tasks.append(
                ResearchTask(
                    id=_ext_id(),
                    source=ResearchSource.WEB,
                    query=competitor_query,
                    purpose="Analyze competitor implementations and features",
                    pass_number=1,
                    category="external",
                    estimated_seconds=60,
                )
            )

        # Market validation
        external_tasks.append(
            ResearchTask(
                id=_ext_id(),
                source=ResearchSource.WEB,
                query=f"{feature_desc} market validation {brand} {market}",
                purpose="Validate market demand and identify similar solutions",
                pass_number=1,
                category="external",
                estimated_seconds=60,
            )
        )

        # Similar products / industry benchmarks
        external_tasks.append(
            ResearchTask(
                id=_ext_id(),
                source=ResearchSource.GEMINI_DEEP_RESEARCH,
                query=(
                    f"How do leading companies implement {feature_desc}? "
                    f"Best practices, UX patterns, technical approaches "
                    f"for {brand} in {market}"
                ),
                purpose="Research best practices and implementation patterns from industry",
                pass_number=1,
                category="external",
                estimated_seconds=120,
            )
        )

        # ----------------------------------------------------------------
        # PASS 2: Targeted follow-up (placeholder tasks, refined at runtime)
        # ----------------------------------------------------------------

        pass_1_int_ids = [t.id for t in internal_tasks if t.pass_number == 1]
        internal_tasks.append(
            ResearchTask(
                id=_int_id(),
                source=ResearchSource.BRAIN,
                query="[Generated from pass 1 gaps]",
                purpose="Deep-dive into entities and relationships found in pass 1",
                pass_number=2,
                category="internal",
                estimated_seconds=30,
                depends_on=pass_1_int_ids,
            )
        )

        internal_tasks.append(
            ResearchTask(
                id=_int_id(),
                source=ResearchSource.JIRA,
                query="[Generated from pass 1 gaps]",
                purpose="Follow up on specific tickets, linked epics, and related work",
                pass_number=2,
                category="internal",
                estimated_seconds=30,
                depends_on=pass_1_int_ids,
            )
        )

        pass_1_ext_ids = [t.id for t in external_tasks if t.pass_number == 1]
        external_tasks.append(
            ResearchTask(
                id=_ext_id(),
                source=ResearchSource.WEB,
                query="[Generated from pass 1 gaps]",
                purpose="Targeted follow-up on market gaps and competitor details",
                pass_number=2,
                category="external",
                estimated_seconds=60,
                depends_on=pass_1_ext_ids,
            )
        )

        # Calculate totals
        all_tasks = internal_tasks + external_tasks
        estimated_total = sum(t.estimated_seconds for t in all_tasks)

        # Extract hit counts
        hit_counts = {
            source: data.get("hit_count", 0)
            for source, data in first_pass_data.items()
            if isinstance(data, dict)
        }

        return ResearchPlan(
            feature_title=questionnaire.feature_description
            or questionnaire.user_problem
            or "Untitled Feature",
            questionnaire_summary=questionnaire.to_dict(),
            internal_tasks=internal_tasks,
            external_tasks=external_tasks,
            first_pass_hits=hit_counts,
            estimated_total_seconds=estimated_total,
        )

    def challenge_plan(self, plan: ResearchPlan) -> ResearchPlan:
        """
        Orthogonally challenge the research plan for completeness.

        Args:
            plan: The research plan to challenge

        Returns:
            Updated plan with challenge feedback
        """
        try:
            from pm_os_base.tools.util.model_bridge import (
                detect_active_model,
                get_challenger_model,
            )
        except ImportError:
            try:
                from util.model_bridge import detect_active_model, get_challenger_model
            except ImportError:
                plan.challenged = False
                plan.challenge_feedback = "Challenge skipped -- model_bridge unavailable"
                return plan

        try:
            active = detect_active_model()
            challenger = get_challenger_model(active)
            logger.info(
                f"Challenging plan with {challenger} (active: {active})"
            )
            plan.challenged = True
            plan.challenge_feedback = (
                f"Plan reviewed by orthogonal challenger ({challenger}). "
                f"{plan.total_tasks} tasks across {len(plan.first_pass_hits)} sources."
            )
        except Exception as e:
            logger.warning(f"Plan challenge failed: {e}")
            plan.challenged = False
            plan.challenge_feedback = f"Challenge failed -- {e}"

        return plan

    def format_plan_for_display(self, plan: ResearchPlan) -> str:
        """
        Format the research plan as a readable Markdown table for user review.

        Args:
            plan: The research plan to display

        Returns:
            Markdown string with plan summary and task table
        """
        lines = ["## Research Plan\n"]

        # Summary
        lines.append(f"**Feature:** {plan.feature_title}")
        lines.append(
            f"**Total Tasks:** {plan.total_tasks} "
            f"({len(plan.pass_1_tasks)} pass 1, {len(plan.pass_2_tasks)} pass 2)"
        )
        lines.append("")

        # First-pass hits
        if plan.first_pass_hits:
            lines.append("### First-Pass Scan Results")
            lines.append("| Source | Hits |")
            lines.append("|--------|------|")
            for source, count in sorted(plan.first_pass_hits.items()):
                lines.append(f"| {source.title()} | {count} |")
            lines.append("")

        # Available sources
        available = [
            s for s in plan.available_sources if s.status != SourceStatus.UNAVAILABLE
        ]
        if available:
            lines.append(
                f"**Available Sources:** {', '.join(s.source.value for s in available)}"
            )
            lines.append("")

        # Internal tasks
        if plan.internal_tasks:
            lines.append("### Internal Research Tasks")
            lines.append("| # | Source | Purpose | Pass |")
            lines.append("|---|--------|---------|------|")
            for task in plan.internal_tasks:
                lines.append(
                    f"| {task.id} | {task.source.value} | {task.purpose} | {task.pass_number} |"
                )
            lines.append("")

        # External tasks
        if plan.external_tasks:
            lines.append("### External Research Tasks")
            lines.append("| # | Source | Purpose | Pass |")
            lines.append("|---|--------|---------|------|")
            for task in plan.external_tasks:
                lines.append(
                    f"| {task.id} | {task.source.value} | {task.purpose} | {task.pass_number} |"
                )
            lines.append("")

        # Challenge status
        if plan.challenged:
            lines.append(f"**Challenge Status:** {plan.challenge_feedback}")
        else:
            lines.append("**Challenge Status:** Not yet challenged")

        return "\n".join(lines)


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def _build_search_terms(questionnaire: QuestionnaireResult) -> str:
    """Build search query from questionnaire answers."""
    parts = []
    if questionnaire.feature_description:
        desc = questionnaire.feature_description
        if "." in desc[:100]:
            parts.append(desc[: desc.index(".") + 1])
        else:
            parts.append(desc[:100])
    elif questionnaire.user_problem:
        parts.append(questionnaire.user_problem[:100])

    if questionnaire.product:
        parts.append(questionnaire.product)
    elif questionnaire.brand:
        parts.append(questionnaire.brand)

    return " ".join(parts).strip()


def _build_competitor_query(questionnaire: QuestionnaireResult) -> str:
    """Build a competitor-focused search query."""
    parts = []
    if questionnaire.competitors:
        parts.append(" vs ".join(questionnaire.competitors[:3]))
    if questionnaire.feature_description:
        parts.append(questionnaire.feature_description[:80])
    if questionnaire.brand:
        parts.append(questionnaire.brand)
    return " ".join(parts).strip()
