#!/usr/bin/env python3
"""
PM-OS Career Plan Generator (v5.0)

Generates and manages career development plans for team members.
Supports create, WHAT/HOW narrative generation, status tracking,
and log syncing from 1:1 notes and context documents.

Usage:
    from pm_os_career.tools.career_plan_generator import CareerPlanGenerator
"""

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# v5 shared utils
try:
    from pm_os_base.tools.core.config_loader import get_config
except ImportError:
    from config_loader import get_config

try:
    from pm_os_base.tools.core.path_resolver import get_paths
except ImportError:
    from path_resolver import get_paths

# Brain is optional
try:
    from pm_os_brain.tools.brain_core.brain_loader import BrainLoader
    HAS_BRAIN = True
except ImportError:
    HAS_BRAIN = False


# --- Data Classes ---

@dataclass
class PersonInfo:
    """Resolved person information."""
    name: str
    slug: str
    role: str = ""
    team: str = ""
    category: str = "reports"  # reports, manager, stakeholders
    career_dir: Optional[Path] = None


@dataclass
class CareerPlanStatus:
    """Status of a career plan."""
    person_name: str
    cycle: str
    plan_exists: bool = False
    project_log_exists: bool = False
    feedback_log_exists: bool = False
    project_count: int = 0
    feedback_count: int = 0
    last_sync: Optional[str] = None
    what_complete: bool = False
    how_complete: bool = False


@dataclass
class LogEntry:
    """A project or feedback log entry."""
    date: str
    content: str
    source: str = ""
    category: str = ""
    impact: str = ""


# --- Constants ---

DEFAULT_COMPETENCY_DIMENSIONS = [
    "Speed & Agility",
    "Data-Drivenness",
    "Egolessness",
    "Customer Centricity",
    "Ownership",
]

CAREER_PLAN_TEMPLATE = """# Career Plan: {person_name}

**Cycle:** {cycle}
**Last Updated:** {date}
**Status:** Draft

---

## SECTION 1: BACKGROUND INFORMATION

| Field | Value |
|-------|-------|
| Candidate's Name | {person_name} |
| Proposed New Career Step | |
| Manager | {manager_name} |
| Proposed New Title | |
| Hire Date | |
| Current FOODIE Rating WHAT | |
| Tenure (in months) | |
| Current FOODIE Rating HOW | |
| Last Promotion | |
| Last FOODIE Rating | |
| Time in current role (in months) | |
| # of Direct Reports | |
| Current Career Step | |
| Organization / Department / Team | {org_context} |

---

## THE FUTURE ROLE

> *To be filled by employee/manager*

Compare the candidate's previous role, please outline briefly the change of scope, \
impact and key metrics of the future role and describe the factors which make the \
role more complex (i.e. global expansions, high growth, incubation project).

[Describe the change of scope, impact and key metrics of the future role]

---

## SECTION 2: PROMOTION CASE

### Business Need

> *To be filled by employee/manager*

Please explain briefly the business need for the promotion? (1-2 paragraphs)

[Explain the business need for the promotion]

---

### Readiness for Promotion

#### WHAT (Body of Work)

> *Updated via: `/team career-plan -WHAT {person_name} {cycle}`*
> *3-5 paragraphs describing body of work at the next level including \
key deliverables and their complexity referring to the Career Framework*

[To be generated - run `/team career-plan -WHAT {person_name} {cycle}`]

---

#### HOW (Behavioral Evidence)

> *Updated via: `/team career-plan -HOW {person_name} {cycle}`*
> *3-5 paragraphs describing how they achieved deliverables referring to \
the Competency Framework including how they exemplify DNA values at the next level*

[To be generated - run `/team career-plan -HOW {person_name} {cycle}`]

---

### Key Risks to Coach/Manage

> *To be filled by manager*

(2-3 paragraphs describing what the risks might be to promoting them to the next \
level and mitigation strategies)

[Describe risks and mitigation strategies]

---

### Peer Feedback

> *Collect from 2-3 peers at target level*

[To be collected]

---

*Generated by PM-OS Career Plugin v5.0*
"""

PROJECT_LOG_TEMPLATE = """# Project Log: {person_name}

> Running log of projects tracked for career planning. \
Auto-updated by `/team career-plan -sync` and context updates.

## Log Entries

| Date | Project | Role | Status | Impact | Source |
|------|---------|------|--------|--------|--------|

---

## Project Details

*No projects logged yet. Run `/team career-plan -sync {person_name}` to populate.*
"""

FEEDBACK_LOG_TEMPLATE = """# Feedback Log: {person_name}

> Running log of feedback tracked for career planning. \
Auto-updated after 1:1s by `/team career-plan -sync` and context updates.

## Competency Mapping Reference

| Dimension | Indicators |
|-----------|------------|
{dimension_rows}

---

## Log Entries

| Date | Type | Summary | Dimension | Source |
|------|------|---------|-----------|--------|

---

## Detailed Feedback Entries

*No feedback logged yet. Run `/team career-plan -sync {person_name}` to populate.*
"""


class CareerPlanGenerator:
    """Generates and manages career plans for team members."""

    def __init__(
        self,
        config: Optional[Any] = None,
        paths: Optional[Any] = None,
    ):
        self.config = config or get_config()
        self.paths = paths or get_paths()
        self._brain_loader = None

    @property
    def manager_name(self) -> str:
        """Get the manager's name from config."""
        return self.config.get("user.name", "")

    @property
    def team_dir(self) -> Path:
        """Get the team directory path."""
        return Path(self.paths.user) / "team"

    @property
    def competency_dimensions(self) -> List[str]:
        """Get competency dimensions from config or defaults."""
        configured = self.config.get("career.competency_dimensions")
        if configured and isinstance(configured, list):
            return configured
        return DEFAULT_COMPETENCY_DIMENSIONS

    def _get_brain_loader(self) -> Optional[Any]:
        """Get brain loader if available."""
        if not HAS_BRAIN:
            return None
        if self._brain_loader is None:
            try:
                self._brain_loader = BrainLoader(paths=self.paths)
            except Exception:
                logger.debug("Brain loader init failed, continuing without Brain")
        return self._brain_loader

    def _slugify(self, name: str) -> str:
        """Convert a name to a slug (lowercase, hyphenated)."""
        slug = name.lower().strip()
        slug = re.sub(r"[^a-z0-9\s-]", "", slug)
        slug = re.sub(r"[\s_]+", "-", slug)
        slug = re.sub(r"-+", "-", slug)
        return slug.strip("-")

    def resolve_person(self, name: str) -> Optional[PersonInfo]:
        """Resolve a person by name from config or Brain."""
        name_lower = name.lower().strip()
        slug = self._slugify(name)

        # Check direct reports
        reports = self.config.get("team.reports", [])
        for report in reports:
            report_name = ""
            report_role = ""
            report_team = ""
            if isinstance(report, dict):
                report_name = report.get("name", "")
                report_role = report.get("role", "")
                report_team = report.get("team", "")
            elif isinstance(report, str):
                report_name = report

            if report_name and name_lower in report_name.lower():
                person_slug = self._slugify(report_name)
                career_dir = self.team_dir / "reports" / person_slug / "career"
                return PersonInfo(
                    name=report_name,
                    slug=person_slug,
                    role=report_role,
                    team=report_team,
                    category="reports",
                    career_dir=career_dir,
                )

        # Check manager
        manager = self.config.get("team.manager", {})
        if manager:
            mgr_name = manager.get("name", "") if isinstance(manager, dict) else str(manager)
            if mgr_name and name_lower in mgr_name.lower():
                person_slug = self._slugify(mgr_name)
                career_dir = self.team_dir / "manager" / person_slug / "career"
                return PersonInfo(
                    name=mgr_name,
                    slug=person_slug,
                    role=manager.get("role", "") if isinstance(manager, dict) else "",
                    category="manager",
                    career_dir=career_dir,
                )

        # Check stakeholders
        stakeholders = self.config.get("team.stakeholders", [])
        for stakeholder in stakeholders:
            sh_name = ""
            sh_role = ""
            if isinstance(stakeholder, dict):
                sh_name = stakeholder.get("name", "")
                sh_role = stakeholder.get("role", "")
            elif isinstance(stakeholder, str):
                sh_name = stakeholder

            if sh_name and name_lower in sh_name.lower():
                person_slug = self._slugify(sh_name)
                career_dir = self.team_dir / "stakeholders" / person_slug / "career"
                return PersonInfo(
                    name=sh_name,
                    slug=person_slug,
                    role=sh_role,
                    category="stakeholders",
                    career_dir=career_dir,
                )

        # Try Brain entity lookup
        brain = self._get_brain_loader()
        if brain:
            try:
                entity = brain.search(name)
                if entity:
                    entity_name = getattr(entity, "name", name)
                    person_slug = self._slugify(entity_name)
                    career_dir = self.team_dir / "reports" / person_slug / "career"
                    return PersonInfo(
                        name=entity_name,
                        slug=person_slug,
                        role=getattr(entity, "role", ""),
                        category="reports",
                        career_dir=career_dir,
                    )
            except Exception:
                logger.debug("Brain search failed for %s", name)

        # Fallback: create from name
        logger.info("Person '%s' not found in config or Brain; using name as-is", name)
        career_dir = self.team_dir / "reports" / slug / "career"
        return PersonInfo(
            name=name,
            slug=slug,
            category="reports",
            career_dir=career_dir,
        )

    def detect_cycle(self, cycle: Optional[str] = None) -> str:
        """Detect or validate the career cycle."""
        if cycle and re.match(r"^[SW]\d{4}$", cycle):
            return cycle
        now = datetime.now()
        year = now.year
        if now.month <= 4:
            return "S%d" % (year - 1)
        return "S%d" % year

    def create_plan(
        self,
        name: str,
        cycle: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Create a career plan directory and files for a team member."""
        person = self.resolve_person(name)
        if not person:
            return {"success": False, "error": "Could not resolve person: %s" % name}

        cycle = self.detect_cycle(cycle)
        career_dir = person.career_dir
        career_dir.mkdir(parents=True, exist_ok=True)

        # Determine org context
        org_parts = []
        department = self.config.get("team.department", "")
        if department:
            org_parts.append(department)
        if person.team:
            org_parts.append(person.team)
        org_context = " / ".join(org_parts) if org_parts else ""

        created_files = []

        # Career plan
        plan_path = career_dir / ("Career_Plan_%s.md" % cycle)
        if not plan_path.exists():
            content = CAREER_PLAN_TEMPLATE.format(
                person_name=person.name,
                cycle=cycle,
                date=datetime.now().strftime("%Y-%m-%d"),
                manager_name=self.manager_name,
                org_context=org_context,
            )
            plan_path.write_text(content, encoding="utf-8")
            created_files.append(str(plan_path))

        # Project log
        project_log_path = career_dir / "project_log.md"
        if not project_log_path.exists():
            content = PROJECT_LOG_TEMPLATE.format(person_name=person.name)
            project_log_path.write_text(content, encoding="utf-8")
            created_files.append(str(project_log_path))

        # Feedback log
        feedback_log_path = career_dir / "feedback_log.md"
        if not feedback_log_path.exists():
            dim_rows = "\n".join(
                "| %s | |" % dim for dim in self.competency_dimensions
            )
            content = FEEDBACK_LOG_TEMPLATE.format(
                person_name=person.name,
                dimension_rows=dim_rows,
            )
            feedback_log_path.write_text(content, encoding="utf-8")
            created_files.append(str(feedback_log_path))

        return {
            "success": True,
            "person": person.name,
            "cycle": cycle,
            "career_dir": str(career_dir),
            "created_files": created_files,
            "already_existed": len(created_files) < 3,
        }

    def get_status(self, name: str, cycle: Optional[str] = None) -> CareerPlanStatus:
        """Get the status of a career plan."""
        person = self.resolve_person(name)
        cycle = self.detect_cycle(cycle)

        status = CareerPlanStatus(person_name=person.name, cycle=cycle)
        career_dir = person.career_dir

        if not career_dir or not career_dir.exists():
            return status

        plan_path = career_dir / ("Career_Plan_%s.md" % cycle)
        status.plan_exists = plan_path.exists()

        project_log_path = career_dir / "project_log.md"
        status.project_log_exists = project_log_path.exists()

        feedback_log_path = career_dir / "feedback_log.md"
        status.feedback_log_exists = feedback_log_path.exists()

        if status.project_log_exists:
            content = project_log_path.read_text(encoding="utf-8")
            status.project_count = len(re.findall(r"^\| \d{4}-\d{2}-\d{2}", content, re.MULTILINE))

        if status.feedback_log_exists:
            content = feedback_log_path.read_text(encoding="utf-8")
            status.feedback_count = len(re.findall(r"^\| \d{4}-\d{2}-\d{2}", content, re.MULTILINE))

        if status.plan_exists:
            plan_content = plan_path.read_text(encoding="utf-8")
            status.what_complete = "[To be generated" not in plan_content.split("#### WHAT")[1] if "#### WHAT" in plan_content else False
            status.how_complete = "[To be generated" not in plan_content.split("#### HOW")[1] if "#### HOW" in plan_content else False

        return status

    def load_project_log(self, person: PersonInfo) -> List[LogEntry]:
        """Load project log entries for a person."""
        log_path = person.career_dir / "project_log.md"
        if not log_path.exists():
            return []

        content = log_path.read_text(encoding="utf-8")
        entries = []
        for match in re.finditer(
            r"^\| (\d{4}-\d{2}-\d{2}) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|",
            content,
            re.MULTILINE,
        ):
            entries.append(LogEntry(
                date=match.group(1).strip(),
                content=match.group(2).strip(),
                category=match.group(3).strip(),
                source=match.group(6).strip(),
                impact=match.group(5).strip(),
            ))
        return entries

    def load_feedback_log(self, person: PersonInfo) -> List[LogEntry]:
        """Load feedback log entries for a person."""
        log_path = person.career_dir / "feedback_log.md"
        if not log_path.exists():
            return []

        content = log_path.read_text(encoding="utf-8")
        entries = []
        for match in re.finditer(
            r"^\| (\d{4}-\d{2}-\d{2}) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|",
            content,
            re.MULTILINE,
        ):
            entries.append(LogEntry(
                date=match.group(1).strip(),
                content=match.group(3).strip(),
                category=match.group(2).strip(),
                source=match.group(5).strip(),
                impact=match.group(4).strip(),
            ))
        return entries

    def gather_oneonone_context(self, person: PersonInfo) -> List[Dict[str, str]]:
        """Gather context from 1:1 meeting notes."""
        oneonone_dir = self.team_dir / person.category / person.slug / "1on1s"
        if not oneonone_dir.exists():
            return []

        notes = []
        for note_file in sorted(oneonone_dir.glob("*.md"), reverse=True)[:10]:
            try:
                content = note_file.read_text(encoding="utf-8")
                notes.append({
                    "file": note_file.name,
                    "content": content[:2000],
                })
            except Exception:
                continue
        return notes

    def sync_logs(self, name: str) -> Dict[str, Any]:
        """Sync project and feedback logs from 1:1 notes and context."""
        person = self.resolve_person(name)
        if not person or not person.career_dir:
            return {"success": False, "error": "Could not resolve person"}

        oneonone_context = self.gather_oneonone_context(person)

        return {
            "success": True,
            "person": person.name,
            "oneonone_notes_found": len(oneonone_context),
            "brain_available": HAS_BRAIN,
            "sync_date": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "message": "Context gathered. Use AI synthesis to extract and append log entries.",
        }

    def get_what_context(self, name: str, cycle: Optional[str] = None) -> Dict[str, Any]:
        """Gather all context needed to generate the WHAT section."""
        person = self.resolve_person(name)
        cycle = self.detect_cycle(cycle)

        projects = self.load_project_log(person)
        oneonone_notes = self.gather_oneonone_context(person)

        brain_context = None
        brain = self._get_brain_loader()
        if brain:
            try:
                brain_context = brain.search(person.name)
            except Exception:
                pass

        return {
            "person": person.name,
            "cycle": cycle,
            "projects": [
                {"date": p.date, "content": p.content, "impact": p.impact}
                for p in projects
            ],
            "oneonone_count": len(oneonone_notes),
            "brain_context": brain_context is not None,
            "plan_path": str(person.career_dir / ("Career_Plan_%s.md" % cycle)),
        }

    def get_how_context(self, name: str, cycle: Optional[str] = None) -> Dict[str, Any]:
        """Gather all context needed to generate the HOW section."""
        person = self.resolve_person(name)
        cycle = self.detect_cycle(cycle)

        feedback = self.load_feedback_log(person)
        oneonone_notes = self.gather_oneonone_context(person)

        return {
            "person": person.name,
            "cycle": cycle,
            "feedback": [
                {"date": f.date, "type": f.category, "content": f.content, "dimension": f.impact}
                for f in feedback
            ],
            "oneonone_count": len(oneonone_notes),
            "dimensions": self.competency_dimensions,
            "plan_path": str(person.career_dir / ("Career_Plan_%s.md" % cycle)),
        }


# --- CLI for testing ---
if __name__ == "__main__":
    import json

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    generator = CareerPlanGenerator()
    manager = generator.manager_name
    print("=== Career Plan Generator ===")
    print("Manager: %s" % manager)
    print("Team dir: %s" % generator.team_dir)
    print("Cycle: %s" % generator.detect_cycle())
    print("Dimensions: %s" % generator.competency_dimensions)
    print("Brain available: %s" % HAS_BRAIN)
