#!/usr/bin/env python3
"""
PRD Generator using Google Deep Research

Uses Deep Research API to generate comprehensive PRDs by researching
internal documentation and web sources.

Usage:
    python3 prd_generator.py --topic "Add OTP to Meal Kit"
    python3 prd_generator.py --update Products/Meal_Kit/OTP_PRD.md --instructions "Add competitor analysis"
    python3 prd_generator.py --setup   # Initialize file store (run once)
"""

import argparse
import json
import os
import sys
import time
import warnings
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Add common directory to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
import config_loader

# Suppress experimental warnings
warnings.filterwarnings("ignore", message=".*experimental.*")

# Constants
BASE_DIR = Path(__file__).parent
CONFIG_FILE = BASE_DIR / "config.json"
ROOT_DIR = config_loader.get_root_path()

# PRD Template Prompt
PRD_TEMPLATE = """You are a senior Product Manager at a food-tech company creating a PRD (Product Requirements Document).

## Topic
{topic}

## Research Instructions

Research the following from available sources:
- Existing product specs and proposals for related features
- Recent decisions and priorities from context files
- Stakeholder context and team information
- Related planning documents and initiatives

Also consider:
- Competitor approaches to similar features
- Industry best practices
- Relevant technical patterns

## PRD Structure

Generate a PRD with this exact structure:

# [Feature Name]: [Concise Subtitle]

**Date:** {date}
**Author:** AI-Generated (Deep Research)
**Status:** Draft

---

## 1. Purpose
[1-2 paragraphs explaining what problem this solves and why it matters now]

## 2. Current State / Problem
**"[A compelling quote or summary]"**
- [3-5 bullet points describing pain points with evidence]

## 3. Strategic Solution
**[Strategy name or approach]**
- **Strategy:** [1-2 sentence description]
- **Philosophy:** [Core principle guiding the approach]

### Scope Table
| Feature | v0 Scope | v1 Scope |
|---------|----------|----------|
| [Feature 1] | [Minimal] | [Full] |
| [Feature 2] | [Minimal] | [Full] |

## 4. Business Impact
**Hypothesis:** [Core hypothesis]

### Projected Impact
| Lever | Mechanism | Conservative Impact | Revenue/Metric Impact |
|-------|-----------|---------------------|----------------------|
| [Lever 1] | [How it works] | [%] | [$$] |
| [Lever 2] | [How it works] | [%] | [$$] |

*Assumptions: [Key assumptions listed]*

## 5. Technical Strategy
- **Architecture:** [Key technical approach]
- **Dependencies:** [Systems/teams needed]
- **Integration:** [How it connects to existing systems]

## 6. Recommendations
1. [Specific recommendation with rationale]
2. [Specific recommendation with rationale]
3. [Specific recommendation with rationale]

---

## References
- [Link to relevant internal doc 1]
- [Link to relevant internal doc 2]

---
*Generated by Deep Research on {date}*

## Format Requirements
- Use Markdown with proper headers
- Include data tables where appropriate
- Be specific with numbers and metrics (make reasonable estimates with clear assumptions)
- Cite sources from the uploaded documents when possible
- Keep it actionable and concise (aim for 2-3 pages)
"""

PRD_UPDATE_TEMPLATE = """You are a senior Product Manager updating an existing PRD.

## Existing PRD
{existing_prd}

## Update Instructions
{instructions}

## Research Instructions
Research available sources to gather information needed for the update.
Focus specifically on what the update instructions request.

## Output Requirements
1. Maintain the existing structure of the PRD
2. Add [UPDATED] markers next to sections that changed significantly
3. Keep the original date but add "Last Updated: {date}"
4. Preserve all original content that doesn't need updating
5. Add new sections only if explicitly needed
6. Update the References section with any new sources used

Output the complete updated PRD in Markdown format.
"""


def load_config() -> Dict[str, Any]:
    """Load configuration."""
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE, "r") as f:
            return json.load(f)
    return {}


def save_config(config: Dict[str, Any]):
    """Save configuration."""
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)


def get_genai_client():
    """Get authenticated Gemini client (new SDK)."""
    from google import genai

    gemini_config = config_loader.get_gemini_config()
    api_key = gemini_config.get("api_key")

    if not api_key:
        print("Error: GEMINI_API_KEY not set in environment", file=sys.stderr)
        sys.exit(1)

    return genai.Client(api_key=api_key)


def poll_interaction(
    client, interaction_id: str, max_time: int = 600, interval: int = 10
) -> Dict:
    """Poll for interaction completion."""
    start_time = time.time()

    while True:
        elapsed = time.time() - start_time
        if elapsed > max_time:
            raise TimeoutError(f"Research timed out after {max_time} seconds")

        try:
            result = client.interactions.get(id=interaction_id)
            status = result.status

            minutes = int(elapsed // 60)
            seconds = int(elapsed % 60)
            print(
                f"  Researching... ({minutes}m {seconds}s) - Status: {status}", end="\r"
            )

            if status == "completed":
                print()  # New line after progress
                return result
            elif status == "failed":
                print()
                raise Exception(f"Research failed")

        except Exception as e:
            if "not found" not in str(e).lower() and "failed" not in str(e).lower():
                # Log transient errors but continue polling
                pass

        time.sleep(interval)


def generate_prd_with_deep_research(
    topic: str, store_name: Optional[str] = None
) -> str:
    """Generate PRD using Deep Research agent."""
    from google import genai
    from google.genai import types

    gemini_config = config_loader.get_gemini_config()
    api_key = gemini_config.get("api_key")

    if not api_key:
        print("Error: GEMINI_API_KEY not set in environment", file=sys.stderr)
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    config = load_config()

    agent = config.get("agent", "deep-research-pro-preview-12-2025")
    date = datetime.now().strftime("%Y-%m-%d")

    prompt = PRD_TEMPLATE.format(topic=topic, date=date)

    print(f"Starting Deep Research for: {topic}")
    print(f"Using agent: {agent}")

    # Build tools config
    # ISOLATION TEST: Only Google Search, raw dict

    # file_search_tool = None
    # if store_name:
    #     file_search_tool = types.FileSearch(
    #         file_search_store_names=[store_name]
    #     )
    #     print(f"File Search store: {store_name}")

    # tool = types.Tool(
    #     file_search=file_search_tool,
    #     google_search=types.GoogleSearch(),
    #     function_declarations=[] # Explicitly empty to prevent 'Missing type' error
    # )

    # tools_config = [tool]

    # Build tools config - must use dict format for interactions API
    # Note: google_search and file_search cannot be combined (API limitation)
    tools_config = []

    if store_name:
        # Use file search for internal docs (prioritize internal knowledge)
        tools_config.append(
            {"type": "file_search", "file_search_store_names": [store_name]}
        )
        print(f"Using File Search store: {store_name}")
    else:
        # Fall back to Google Search for web research
        tools_config.append({"type": "google_search"})
        print("Using Google Search (no file store configured)")

    try:
        interaction = client.interactions.create(
            input=prompt, agent=agent, background=True, tools=tools_config
        )

        print(f"Interaction ID: {interaction.id}")

        # Poll for completion
        result = poll_interaction(
            client,
            interaction.id,
            max_time=config.get("max_poll_time_seconds", 600),
            interval=config.get("poll_interval_seconds", 10),
        )

        # Extract text from outputs
        if result.outputs:
            # Find the text output
            for output in result.outputs:
                if hasattr(output, "text") and output.text:
                    return output.text
                elif hasattr(output, "parts"):
                    for part in output.parts:
                        if hasattr(part, "text") and part.text:
                            return part.text

            # Fallback: convert entire output to string
            return str(result.outputs[-1])

        return "No output generated"

    except Exception as e:
        error_msg = str(e)
        if (
            "429" in error_msg
            or "quota" in error_msg.lower()
            or "rate" in error_msg.lower()
        ):
            print(
                f"\nDeep Research quota exceeded. Falling back to standard generation...",
                file=sys.stderr,
            )
        else:
            print(f"\nDeep Research error: {e}", file=sys.stderr)
            print("Falling back to standard generation...", file=sys.stderr)

        return generate_prd_standard(topic)


def generate_prd_standard(topic: str) -> str:
    """Fallback: Generate PRD using standard Gemini API."""
    import google.generativeai as genai

    gemini_config = config_loader.get_gemini_config()
    api_key = gemini_config.get("api_key")
    model_name = gemini_config.get("model", "gemini-2.5-flash")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(model_name)

    date = datetime.now().strftime("%Y-%m-%d")
    prompt = PRD_TEMPLATE.format(topic=topic, date=date)

    print(f"Generating with {model_name}...")
    response = model.generate_content(prompt)

    return response.text


def update_prd(existing_path: str, instructions: str) -> str:
    """Update an existing PRD with new research."""
    import google.generativeai as genai

    # Read existing PRD
    with open(existing_path, "r", encoding="utf-8") as f:
        existing_prd = f.read()

    gemini_config = config_loader.get_gemini_config()
    api_key = gemini_config.get("api_key")
    model_name = gemini_config.get("model", "gemini-2.5-flash")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(model_name)

    date = datetime.now().strftime("%Y-%m-%d")
    prompt = PRD_UPDATE_TEMPLATE.format(
        existing_prd=existing_prd, instructions=instructions, date=date
    )

    print(f"Updating PRD: {existing_path}")
    print(f"Instructions: {instructions}")
    print(f"Using model: {model_name}")

    response = model.generate_content(prompt)
    return response.text


def sanitize_filename(topic: str) -> str:
    """Convert topic to safe filename."""
    safe = "".join(c if c.isalnum() or c in " -_" else "" for c in topic)
    safe = safe.replace(" ", "_")
    return safe[:50]


def main():
    parser = argparse.ArgumentParser(description="Generate PRDs using Deep Research")
    parser.add_argument("--topic", type=str, help="Topic for new PRD")
    parser.add_argument(
        "--update", type=str, metavar="FILE", help="Path to existing PRD to update"
    )
    parser.add_argument(
        "--instructions",
        type=str,
        default="",
        help="Update instructions (with --update)",
    )
    parser.add_argument("--output", type=str, help="Output file path")
    parser.add_argument(
        "--setup", action="store_true", help="Run initial setup (index files)"
    )
    parser.add_argument(
        "--no-deep-research",
        action="store_true",
        help="Use standard generation instead of Deep Research",
    )

    args = parser.parse_args()

    if args.setup:
        # Run setup from file_store_manager
        from file_store_manager import setup_store

        setup_store()
        return 0

    config = load_config()
    store_name = config.get("file_store_id")

    if args.update:
        # Update mode
        if not os.path.exists(args.update):
            print(f"Error: File not found: {args.update}", file=sys.stderr)
            return 1

        instructions = (
            args.instructions or "Review and improve the PRD with latest information"
        )
        result = update_prd(args.update, instructions)

        # Save back to same file or specified output
        output_path = args.output or args.update
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(result)

        print(f"\nPRD updated: {output_path}")

    elif args.topic:
        # Create mode
        if args.no_deep_research:
            result = generate_prd_standard(args.topic)
        else:
            result = generate_prd_with_deep_research(args.topic, store_name)

        # Determine output path
        if args.output:
            output_path = args.output
        else:
            safe_name = sanitize_filename(args.topic)
            date_str = datetime.now().strftime("%Y-%m-%d")
            output_path = ROOT_DIR / "Products" / f"PRD_{safe_name}_{date_str}.md"

        # Ensure directory exists
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Save
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(result)

        print(f"\nPRD generated: {output_path}")

    else:
        parser.print_help()
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
